language: python
python:
  - "3.3"
install:
  - pip install git+git://github.com/TangledWeb/tangled.git#egg=tangled[dev]
  - pip install git+git://github.com/TangledWeb/tangled.web.git#egg=tangled.web[dev]
  - pip install -e .[dev]
script:
  - tangled test --no-coverage
